services:
  backend:
    build: 
      context: ./
      dockerfile: ./dockerfile.dev
    container_name: finance_api
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    env_file:
      - ./.env

  postgres:
    image: postgres:18-alpine
    container_name: finance_postgres
    restart: always
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: masterkey
    ports:
      - "5440:5432"
    volumes:
      - finance_postgres_data:/var/lib/postgresql

volumes:
  finance_postgres_data